In [1]:
import numpy as np

#### Compute the scalar product of two vectors
a vector is a dot/scalar product 
we can calculate it this way: a · b = ax × bx + ay × by

In [3]:
a = [-18, 9]
b = [9, 20]
np.dot(a,b)

18

In [4]:
-18 * 9

-162

In [5]:
9 * 20

180

In [6]:
-162 + 180

18

#### Compute the cross product of two vectors
When a and b start at the origin point (0,0,0), the Cross Product will end at:
cx = aybz − azby, 
cy = azbx − axbz, 
cz = axby − aybx

In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6], [1,2,3]])

In [12]:
np.cross(a,b)

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [13]:
#first vector ay x bz - az x by
2 * 6 - 3 * 5

-3

In [14]:
# az x bx - ax x bz
3 * 4 - 1 * 6

6

In [15]:
# ax x by - ay x bx
1 * 5 - 2 * 4

-3

In [16]:
#second vector ay x bz - az x by
5 * 3 - 6 * 2

3

In [17]:
# az x bx - ax x bz
6 * 1 - 4 * 3

-6

In [18]:
# ax x by - ay x bx
4 * 2 - 5 * 1

3

#### Compute the Hadamard product (entry-wise multiplication) of two vectors.

In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices.

In [19]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
              [7,8]])
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [20]:
1 * 5 

5

In [21]:
2 * 6

12

In [22]:
3 * 7

21

In [23]:
4 * 8

32

#### Compute the sum of two matrices.

In [35]:
X = [[12,7,3],
     [4,5,6],
     [7,8,9]]

Y = [[5,8,1],
     [6,7,8],
     [4,5,9]]

result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

In [36]:
# X is 3 x 3
# Y is 3 x 3
# Results of XY is 3x3 matrix

for i in range(len(X)):  # iterate through rows of X 
   for j in range(len(Y[0])):  # iterate through cols of Y 
       for k in range(len(Y)):  # iterate through rows of Y 
           result[i][j] += X[i][k] * Y[k][j]  

In [37]:
print(result)

[[114, 160, 95], [74, 97, 98], [119, 157, 152]]


In [42]:
#result[0][0] 
12 * 5 + 7 * 6 + 3 * 4

114

In [43]:
#result[0][1]
12 * 8 + 7 * 7 + 3 * 5 

160

In [44]:
#result[0][2]
12 * 1 + 7 * 8 + 3 * 9

95

In [45]:
#result[1][0]
4 * 5 + 5 * 6 + 6 * 4

74

In [46]:
#result[1][1]
4 * 8 + 5 * 7 + 6 * 5

97

In [47]:
#result[1][2]
4 * 1 + 5 * 8 + 6 * 9

98

In [48]:
#result[2][0]
7 * 5 + 8 * 6 + 9 * 4

119

In [49]:
#result[2][1]
7 * 8 + 8 * 7 + 9 * 5

157

In [50]:
#result[2][2]
7 * 1 + 8 * 8 + 9 * 9

152

    result[0][0] = X[0][0] + Y[0][0] = 12 + 5 = 17

    result[0][1] = X[0][1] + Y[0][1] = 7 + 8 = 15

    result[0][2] = X[0][2] + Y[0][2] = 3 + 1 = 4

    result[1][0] = X[1][0] + Y[1][0] = 4 + 6 = 10

    result[1][1] = X[1][1] + Y[1][1] = 5 + 7 = 12

    result[1][2] = X[1][2] + Y[1][2] = 6 + 8 = 14

    result[2][0] = X[2][0] + Y[2][0] = 7 + 4 = 11

    result[2][1] = X[2][1] + Y[2][1] = 8 + 5 = 13

    result[2][2] = X[2][2] + Y[2][2] = 9 + 9 = 18

In [51]:
np.add(X, Y)

array([[17, 15,  4],
       [10, 12, 14],
       [11, 13, 18]])

In [52]:
result = [[X[i][j] + Y[i][j]] for i in range(len(X)) for j in range(len(Y[0]))]

print(result)

[[17], [15], [4], [10], [12], [14], [11], [13], [18]]


In [53]:
np.array(result)

array([[17],
       [15],
       [ 4],
       [10],
       [12],
       [14],
       [11],
       [13],
       [18]])

In [54]:
np.array(result)

array([[17],
       [15],
       [ 4],
       [10],
       [12],
       [14],
       [11],
       [13],
       [18]])

#### Compute the product of two matrices.

In [55]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

#X is 3 x 3, #Y is 3 x 3 matrix
#result of XY is 3 x 3 matrix.
 
for i in range(len(X)):  # iterate through rows of X 
   for j in range(len(Y[0])):  # iterate through cols of Y 
       for k in range(len(Y)):  # iterate through rows of Y 
           result[i][j] += X[i][k] * Y[k][j]  

print(result)

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]


In [56]:
np.dot(X,Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [57]:
np.array(result)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

#### Compute the determinant of an n x n matrix.

In [58]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]
det = np.linalg.det(matrix)
print(det)

17.999999999999996


##### the determinant helps us understand how a matrix changes the size and orientation of shapes or vectors in space, and it's a crucial concept in various areas of mathematics and science.

If the determinant is positive, it means the matrix scales the space, making it larger or smaller. If it's negative, it means the matrix not only scales but also flips the space.

Invertibility: If the determinant is not zero, it means the matrix has an "inverse," which is like the opposite of the matrix. You can use the inverse to undo the effects of the matrix transformation.

##### Whether a positive or negative determinant is considered "good" depends on the context and what you want to achieve with the matrix transformation:

    Positive Determinant (Scaling with Orientation Preservation):
        A positive determinant indicates that the matrix scales the space either by enlarging it or shrinking it. This is often associated with preserving the orientation of shapes.
        In many applications, such as computer graphics, engineering, and physics, a positive determinant is desirable because it means that the transformation maintains the orientation of objects, which is often a desired property.

    Negative Determinant (Scaling with Orientation Reversal):
        A negative determinant indicates that the matrix not only scales the space but also flips it or changes its orientation. This can be useful in certain situations.
        For example, in computer graphics, a negative determinant might be used intentionally to create a mirrored or reflected version of an object.

In summary, whether a positive or negative determinant is "good" depends on the specific goals of the transformation. Positive determinants are often associated with orientation-preserving transformations, while negative determinants imply orientation-reversal or reflection. The choice of determinant sign depends on the desired outcome and the problem being solved.

#### Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [60]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)

In [61]:
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

###### The variable ainv will contain the inverse of the matrix a. The inverse matrix allows you to undo the effects of the original matrix when performing matrix multiplication. 
However, not all matrices have inverses, and it's essential to check the determinant of the matrix before attempting to calculate its inverse to ensure it's non-singular (i.e., its determinant is not zero).