In [1]:
import numpy as np

In [6]:
arr = np.random.randn(4,5)

In [7]:
arr

array([[ 1.23607291, -0.95439318, -0.72883744,  0.18557968, -0.78974586],
       [ 1.03548669, -2.07223131,  0.38509515, -0.02831301, -0.5690189 ],
       [ 1.16050381,  0.87154405,  0.45446349,  0.05735755, -1.92074034],
       [-1.61008832,  0.77249479,  0.55892082,  0.40306635, -1.85420993]])

In [8]:
arr.var()

1.0997236574391338

In [11]:
np.where(arr < 0,0,arr)

array([[1.23607291, 0.        , 0.        , 0.18557968, 0.        ],
       [1.03548669, 0.        , 0.38509515, 0.        , 0.        ],
       [1.16050381, 0.87154405, 0.45446349, 0.05735755, 0.        ],
       [0.        , 0.77249479, 0.55892082, 0.40306635, 0.        ]])

In [14]:
arr.sort()

In [15]:
arr

array([[-0.95439318, -0.78974586, -0.72883744,  0.18557968,  1.23607291],
       [-2.07223131, -0.5690189 , -0.02831301,  0.38509515,  1.03548669],
       [-1.92074034,  0.05735755,  0.45446349,  0.87154405,  1.16050381],
       [-1.85420993, -1.61008832,  0.40306635,  0.55892082,  0.77249479]])